export const CREATE_LXC = 'CRAETE_LXC';
export const CREATE_LXC_SUCCESS = 'CRAETE_LXC_SUCCESS';
export const CREATE_LXC_FAIL = 'CRAETE_LXC_FAIL';

export const FETCH_LXC_LIST = 'FETCH_LXC_LIST';
export const FETCH_LXC_LIST_SUCCESS = 'FETCH_LXC_LIST_SUCCESS';
export const FETCH_LXC_LIST_FAIL = 'FETCH_LXC_LIST_FAIL';
