export const START_AUTHENTICATION = 'START_AUTHENTICATION';
export const START_AUTHENTICATION_SUCCESS = 'START_AUTHENTICATION_SUCCESS';
export const START_AUTHENTICATION_FAIL = 'START_AUTHENTICATION_FAIL';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const USER_SAVED_IN_LOCAL_STORAGE = 'USER_SAVED_IN_LOCAL_STORAGE';
export const SESSION_TIMEOUT = 'SESSION_TIMEOUT';
