export const FETCH_LXC_STATUS = 'FETCH_LXC_STATUS';
export const SOCKET_FETCH_LXC_STATUS_SUCCESS = 'SOCKET_FETCH_LXC_STATUS_SUCCESS';
export const FETCH_LXC_STATUS_FAIL = 'FETCH_LXC_STATUS_FAIL';

export const START_LXC = 'START_LXC';
export const START_LXC_SUCCESS = 'START_LXC_SUCCESS';
export const START_LXC_FAIL = 'START_LXC_FAIL';

export const STOP_LXC = 'STOP_LXC';
export const STOP_LXC_SUCCESS = 'STOP_LXC_SUCCESS';
export const STOP_LXC_FAIL = 'STOP_LXC_FAIL';

export const ASSIGN_LXC = 'ASSIGN_LXC';
export const ASSIGN_LXC_SUCCESS = 'ASSIGN_LXC_SUCCESS';
export const ASSIGN_LXC_FAIL = 'ASSIGN_LXC_FAIL';

export const UNASSIGN_LXC = 'UNASSIGN_LXC';
export const UNASSIGN_LXC_SUCCESS = 'UNASSIGN_LXC_SUCCESS';
export const UNASSIGN_LXC_FAIL = 'UNASSIGN_LXC_FAIL';

export const FETCH_SERVER_INFO = 'FETCH_SERVER_INFO';
export const FETCH_SERVER_INFO_SUCCESS = 'FETCH_SERVER_INFO_SUCCESS';
export const FETCH_SERVER_INFO_FAIL = 'FETCH_LXC_STATUS_FAIL';